name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |        
        sudo apt-get update
        sudo apt-get install openmpi
        sudo apt-get install hdf5

        mkdir build;
        cd build;
        cmake -DCMAKE_CXX_FLAGS=" --coverage -fno-inline -fno-inline-small-functions -fno-default-inline -fprofile-arcs -ftest-coverage " .. ;
        make -j4;

    - name: Test
      run: |
        module load BuildEnv/gcc-12.2.0.lua;
        cd build;
        ctest -j1;
        # TODO: add project specific tests
    - name: Run coverage
      run: |
        module load BuildEnv/gcc-12.2.0.lua;
        cd build;
        lcov --capture --directory . --output-file coverage.info;
        lcov --remove coverage.info '/usr/*' --output-file coverage.info
        lcov --remove coverage.info '/opt/ohpc/pub/compiler/*' --output-file coverage.info
        lcov --remove coverage.info '*_deps*' --output-file coverage.info
        lcov --remove coverage.info '*libs*' --output-file coverage.info
        lcov --list coverage.info
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
